export default {
  LOAD_SECTIONS_REQUEST : 'LOAD_SECTIONS_REQUEST',
  LOAD_SECTIONS_SUCCESS : 'LOAD_SECTIONS_SUCCESS',
  LOAD_SECTIONS_FAILED : 'LOAD_SECTIONS_FAILED',

  LOAD_TODOS_REQUEST : 'LOAD_TODOS_REQUEST',
  LOAD_TODOS_SUCCESS : 'LOAD_TODOS_SUCCESS',
  LOAD_TODOS_FAILED : 'LOAD_TODOS_FAILED',

  ADD_SECTION_SUCCESS : 'ADD_SECTION_SUCCESS',
  ADD_SECTION_REQUEST : 'ADD_SECTION_REQUEST',
  ADD_SECTION_FAILED : 'ADD_SECTION_FAILED',

  DELETE_SECTION_REQUEST: 'DELETE_SECTION_REQUEST',
  DELETE_SECTION_SUCCESS: 'DELETE_SECTION_SUCCESS',
  DELETE_SECTION_FAILED: 'DELETE_SECTION_FAILED',

  DELETE_TODO_REQUEST: 'DELETE_TODO_REQUEST',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  DELETE_TODO_FAILED: 'DELETE_TODO_FAILED',

  CREATE_TODO_SUCCESS : 'CREATE_TODO_SUCCESS',
  CREATE_TODO_REQUEST : 'CREATE_TODO_REQUEST',
  CREATE_TODO_FAILED : 'CREATE_TODO_FAILED'
}
